spring:
  kafka:
    server:
      port: 29092
    consumer:
      group-id: app.2
      bootstrap-servers: localhost:29092


server:
  port: 8008

applications:
  telegram:
    token: 6051693068:AAHwHoJLpSxeRM4TNVC8VBCGZl8957RJ91U   #Токен телеграм бота MessServiceTest1
    url_token: https://api.telegram.org/bot6051693068:AAHwHoJLpSxeRM4TNVC8VBCGZl8957RJ91U/sendMessage
    chat_id: -660748511 #Беседа в телеге Testing

