spring:
  kafka:
    consumer:
      group-id: ${MESSAGE_CONSUMER_GROUP:app.2}
      bootstrap-servers: ${BOOTSTRAP_HOST:localhost:29092}

applications:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:6051693068:AAHwHoJLpSxeRM4TNVC8VBCGZl8957RJ91U}
    chatId: ${TELEGRAM_CHAT_ID:-660748511 }

server:
  port: 8082
